import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import authRoutes from './routes/auth.routes.js';
import tenantRoutes from './routes/tenants.routes.js';
import customerRoutes from './routes/customers.routes.js';
import supplierRoutes from './routes/suppliers.routes.js';
import productRoutes from './routes/products.routes.js';
import invoiceRoutes from './routes/invoices.routes.js';
import purchaseRoutes from './routes/purchases.routes.js';
import returnRoutes from './routes/returns.routes.js';
import paymentRoutes from './routes/payments.routes.js';
import ledgerRoutes from './routes/ledgers.routes.js';
import cashBankRoutes from './routes/cashbank.routes.js';
import accountingRoutes from './routes/accounting.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import reportRoutes from './routes/reports.routes.js';
import userRoutes from './routes/users.routes.js';
import subscriptionRoutes from './routes/subscriptions.routes.js';
import settingsRoutes from './routes/settings.routes.js';
import fileRoutes from './routes/files.routes.js';
import branchRoutes from './routes/branches.routes.js';
import saasAdminRoutes from './routes/saasAdmin.routes.js';
import approvalRoutes from './routes/approvals.routes.js';
import notificationRoutes from './routes/notifications.routes.js';
import auditRoutes from './routes/audit.routes.js';
import statementRoutes from './routes/statements.routes.js';
import chequeRoutes from './routes/cheques.routes.js';
import warrantyRoutes from './routes/warranty.routes.js';
import manufacturingRoutes from './routes/manufacturing.routes.js';
import batchRoutes from './routes/batches.routes.js';
import serviceRoutes from './routes/services.routes.js';
import crmRoutes from './routes/crm.routes.js';
import quotationRoutes from './routes/quotations.routes.js';
import hrRoutes from './routes/hr.routes.js';
import projectRoutes from './routes/projects.routes.js';
import installmentRoutes from './routes/installments.routes.js';
import bankReconciliationRoutes from './routes/bankReconciliation.routes.js';
import assetRoutes from './routes/assets.routes.js';
import multiCurrencyRoutes from './routes/multiCurrency.routes.js';
import loyaltyRoutes from './routes/loyalty.routes.js';
import deliveryRoutes from './routes/delivery.routes.js';
import budgetingRoutes from './routes/budgeting.routes.js';
import campaignRoutes from './routes/campaigns.routes.js';
import dashboardBuilderRoutes from './routes/dashboardBuilder.routes.js';
import { errorHandler, notFound } from './middleware/errorHandler.js';

export const app = express();

app.use(helmet());
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') || '*', credentials: true }));
app.use(express.json({ limit: '2mb' }));

app.get('/', (req, res) => res.json({ message: 'SmartLedger SaaS API is running', version: '4.5.0' }));
app.get('/api/health', (req, res) => res.json({ ok: true, service: 'smartledger-api', time: new Date().toISOString() }));

app.use('/api/auth', authRoutes);
app.use('/api/tenants', tenantRoutes);
app.use('/api/customers', customerRoutes);
app.use('/api/suppliers', supplierRoutes);
app.use('/api/products', productRoutes);
app.use('/api/invoices', invoiceRoutes);
app.use('/api/purchases', purchaseRoutes);
app.use('/api/returns', returnRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/ledgers', ledgerRoutes);
app.use('/api/cashbank', cashBankRoutes);
app.use('/api/accounting', accountingRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/reports', reportRoutes);
app.use('/api/users', userRoutes);
app.use('/api/subscriptions', subscriptionRoutes);
app.use('/api/settings', settingsRoutes);
app.use('/api/files', fileRoutes);
app.use('/api/branches', branchRoutes);
app.use('/api/saas-admin', saasAdminRoutes);
app.use('/api/approvals', approvalRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/audit', auditRoutes);
app.use('/api/statements', statementRoutes);
app.use('/api/cheques', chequeRoutes);
app.use('/api/warranty', warrantyRoutes);
app.use('/api/manufacturing', manufacturingRoutes);
app.use('/api/batches', batchRoutes);
app.use('/api/services', serviceRoutes);
app.use('/api/crm', crmRoutes);
app.use('/api/quotations', quotationRoutes);
app.use('/api/hr', hrRoutes);
app.use('/api/projects', projectRoutes);
app.use('/api/installments', installmentRoutes);
app.use('/api/bank-reconciliation', bankReconciliationRoutes);
app.use('/api/assets', assetRoutes);
app.use('/api/multi-currency', multiCurrencyRoutes);
app.use('/api/loyalty', loyaltyRoutes);
app.use('/api/deliveries', deliveryRoutes);
app.use('/api/budgeting', budgetingRoutes);
app.use('/api/campaigns', campaignRoutes);
app.use('/api/dashboard-builder', dashboardBuilderRoutes);

app.use(notFound);
app.use(errorHandler);
